spring:
  application:
    name: 'Family Finance - Desktop'
  main:
    web-application-type: 'none'
logging:
  structured:
    format:
      file: 'ecs'
  file:
    name: 'log.json'
backend:
  url: 'http://localhost:8080'
styles:
  file: 'styles.json'
counter:
  max-count: 5
  timeout-minutes: 10